# create numpy array

In [17]:
import numpy as np
import random as random

a = np.array([1,2,3])
b= np.array(range(10))
c = np.arange(1,10)
d = np.array(range(1,4),dtype=float)
e = np.array([1,1,0,1,0,0],dtype=bool)
Re = e.astype(float)

f = np.array([random.random() for i in range(10)])
g = np.round(f,2)

print(a)
print(b)
print(c)
print(d)
print(e)
print(Re)
print(f)
print(g)

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1. 2. 3.]
[ True  True False  True False False]
[1. 1. 0. 1. 0. 0.]
[0.75755955 0.1558551  0.13259648 0.6545614  0.85738119 0.91200284
 0.93943466 0.41135847 0.82799069 0.4601497 ]
[0.76 0.16 0.13 0.65 0.86 0.91 0.94 0.41 0.83 0.46]


# shape the array

In [43]:
import numpy as np

t1 = np.arange(12)
t2 = np.array([[1,2,3],[4,5,6]])
t3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
t4 = np.arange(12).reshape((3,4))
t5 = np.arange(24).reshape((2,3,4))
t5 = t5.reshape(1,24)

print(t1)
print(t1.shape)
print(t2)
print(t2.shape)
print(t3)
print(t4)
print(t5.shape[0]*t5.shape[1])
print(t5.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


# numpy array calculate

In [59]:
import numpy as np

t1 = np.arange(12).reshape(4,3)
t2 = np.arange(20,32).reshape(4,3)
t3 = np.array([1,2,3])

print(t1)
print(t2)
print(t3)
print(t1+t2)
print(t1+t3)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]]
[1 2 3]
[[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]]
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]]


# Numpy load file

In [70]:
import numpy as np

Income_file_path = "./Income.csv"

t1 = np.loadtxt(Income_file_path,delimiter=",",skiprows=1,dtype="int")

print(t1)

[[   2    0    1 ...    1    0    0]
 [   3    0    1 ...    1    0    0]
 [   4    1    0 ...    1    0    0]
 ...
 [8991    1    0 ...    1    0    0]
 [8992    1    0 ...    1    0    0]
 [8993    1    0 ...    1    0    0]]


# numpy array transpose

In [72]:
import numpy as np

t1 = np.arange(12).reshape(4,3)

print(t1)
print(t1.transpose())
print(t1.T)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


# numpy array slicing and modify

In [105]:
import numpy as np

t1 = np.arange(12).reshape(4,3)

print(t1)
print(t1[1,:])
print(t1[:,1])

print(t1[:,2:])
print(t1[2:,:])

print(t1[[0,2],:])
print(t1[:,[0,2]])

print(t1[1,2])
print(t1[0:2,0:2])

print(t1[[0,1],[2,2]])

t2 = np.arange(12).reshape(4,3)

t2 = np.where(t2<5,0,5)
print(t2)

t3 = np.arange(12).reshape(4,3)
t3 = t3.clip(3,5)
print(t3)



[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[3 4 5]
[ 1  4  7 10]
[[ 2]
 [ 5]
 [ 8]
 [11]]
[[ 6  7  8]
 [ 9 10 11]]
[[0 1 2]
 [6 7 8]]
[[ 0  2]
 [ 3  5]
 [ 6  8]
 [ 9 11]]
5
[[0 1]
 [3 4]]
[2 5]
[[0 0 0]
 [0 0 5]
 [5 5 5]
 [5 5 5]]
[[3 3 3]
 [3 4 5]
 [5 5 5]
 [5 5 5]]


# array stack operation

In [24]:
import numpy as np
import random as random

t1 = np.arange(0,12).reshape(2,6)
t2 = np.arange(12,24).reshape(2,6)

print(t1)
print(t2)

t3 = np.vstack((t1,t2))
print(t3)

t4 = np.hstack((t1,t2))
print(t4)

t5 = np.eye(3)
print(t5*3)

t6 = np.random.randint(10,20,(4,5))
print(t6)

t7 = np.random.uniform(10,20,(10))
print(t7)

t8 = np.count_nonzero(t7)
print(t8)

t9 = t1.std(axis=1)
print(t9)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]]
[[15 16 12 12 10]
 [15 19 17 19 16]
 [13 16 15 17 19]
 [10 17 16 13 12]]
[14.75634296 18.63621379 10.74023188 10.88033024 10.8626836  14.06378388
 11.2423786  17.36548341 13.23325192 16.07954683]
10
[1.70782513 1.70782513]
